import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { PageHeader } from '../../components/ui/PageHeader';
import { Card } from '../../components/ui/Card';
import { ArrowRight } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const LEVEL_COLORS: Record<number, string> = {
  1: 'bg-orange-100 text-orange-700',
  2: 'bg-blue-100 text-blue-700',
  3: 'bg-green-100 text-green-700',
  4: 'bg-purple-100 text-purple-700',
  5: 'bg-teal-100 text-teal-700',
  6: 'bg-pink-100 text-pink-700',
  7: 'bg-indigo-100 text-indigo-700',
  8: 'bg-yellow-100 text-yellow-700',
  9: 'bg-red-100 text-red-700',
  10: 'bg-gray-100 text-gray-700',
};

export default function LevelIncomePage() {
  const [transactions, setTransactions] = useState<any[]>([]);
  const [totalIncome, setTotalIncome] = useState(0);
  const [levelBreakdown, setLevelBreakdown] = useState<Record<number, number>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchLevelIncome = async () => {
      try {
        setLoading(true);
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        const { data } = await supabase
          .from('level_income_transactions')
          .select('id, new_member_uuid, level_distance, income_generated, status, created_at, members!level_income_transactions_new_member_uuid_fkey(member_profile(full_name))')
          .eq('sponsor_uuid', user.id)
          .order('created_at', { ascending: false });

        if (data) {
          setTransactions(data);
          const total = data.reduce((sum, tx) => sum + Number(tx.income_generated), 0);
          setTotalIncome(total);

          // Aggregate by level
          const breakdown: Record<number, number> = {};
          data.forEach(tx => {
            const lvl = tx.level_distance;
            breakdown[lvl] = (breakdown[lvl] || 0) + Number(tx.income_generated);
          });
          setLevelBreakdown(breakdown);
        }
      } catch (err) {
        console.error('Error fetching level income', err);
      } finally {
        setLoading(false);
      }
    };
    fetchLevelIncome();
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="max-w-4xl mx-auto pb-10 space-y-6"
    >
      <PageHeader
        title="Level Income"
        description="Earnings generated from your multi-level sponsor network (up to 10 levels deep)."
        breadcrumbs={[{ label: 'Business' }, { label: 'Income Dashboard' }, { label: 'Level Income' }]}
      />

      {/* Summary Card */}
      <Card className="text-center p-10">
        <div className="w-16 h-16 bg-[#232F46]/10 rounded-full flex items-center justify-center mx-auto mb-4">
          <ArrowRight className="w-8 h-8 text-[#232F46]" />
        </div>
        <p className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Total Level Income</p>
        {loading ? (
          <p className="text-4xl font-black text-gray-300 animate-pulse">Loading...</p>
        ) : (
          <p className="text-4xl font-black text-[#ED8C32]">₹{totalIncome.toLocaleString()}</p>
        )}

        <div className="mt-8 pt-8 border-t border-gray-100 text-left">
          <h3 className="font-bold text-[#232F46] mb-2">How it works</h3>
          <p className="text-sm text-gray-600">
            Level Income pays you a fixed amount for the activity generated by members in your Sponsor Tree, up to 10 levels deep. Inactive members in the chain are compressed dynamically, ensuring active sponsors always receive their rightful income.
          </p>
        </div>
      </Card>

      {/* Level Breakdown */}
      {!loading && Object.keys(levelBreakdown).length > 0 && (
        <Card>
          <h3 className="font-bold text-[#232F46] mb-4">Income by Level</h3>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
            {Array.from({ length: 10 }, (_, i) => i + 1).map(lvl => (
              <div key={lvl} className="text-center p-3 bg-gray-50 rounded-xl border border-gray-100">
                <span className={`inline-flex items-center justify-center w-8 h-8 rounded-full text-xs font-black mb-2 ${LEVEL_COLORS[lvl] || 'bg-gray-100 text-gray-600'}`}>
                  L{lvl}
                </span>
                <p className="text-sm font-bold text-[#232F46]">₹{(levelBreakdown[lvl] || 0).toLocaleString()}</p>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Transaction History */}
      <Card>
        <h3 className="font-bold text-[#232F46] mb-4">Level Income History</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                <th className="p-3 text-[10px] font-bold text-gray-500 uppercase tracking-wider">Date</th>
                <th className="p-3 text-[10px] font-bold text-gray-500 uppercase tracking-wider">From Member</th>
                <th className="p-3 text-[10px] font-bold text-gray-500 uppercase tracking-wider">Level</th>
                <th className="p-3 text-[10px] font-bold text-gray-500 uppercase tracking-wider">Status</th>
                <th className="p-3 text-[10px] font-bold text-[#ED8C32] uppercase tracking-wider text-right">Income</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {loading && (
                <tr><td colSpan={5} className="p-6 text-center text-sm text-gray-400">Loading...</td></tr>
              )}
              {!loading && transactions.length === 0 && (
                <tr>
                  <td colSpan={5} className="p-6 text-center text-sm text-gray-400">
                    No level income transactions yet. Build your sponsor network to start earning!
                  </td>
                </tr>
              )}
              {transactions.map((tx) => {
                const profile = Array.isArray(tx.members?.member_profile)
                  ? tx.members?.member_profile[0]
                  : tx.members?.member_profile;
                return (
                  <tr key={tx.id} className="hover:bg-gray-50/50 transition-colors">
                    <td className="p-3 text-xs font-medium text-[#232F46]">{new Date(tx.created_at).toLocaleDateString()}</td>
                    <td className="p-3 text-xs text-gray-600">{profile?.full_name || 'Member'}</td>
                    <td className="p-3">
                      <span className={`inline-flex px-2 py-1 text-[10px] font-black rounded-full ${LEVEL_COLORS[tx.level_distance] || 'bg-gray-100 text-gray-600'}`}>
                        Level {tx.level_distance}
                      </span>
                    </td>
                    <td className="p-3">
                      <span className="inline-flex px-2 py-1 text-[10px] font-bold uppercase rounded-full bg-green-100 text-green-700">
                        {tx.status}
                      </span>
                    </td>
                    <td className="p-3 text-right font-bold text-[#ED8C32]">+₹{Number(tx.income_generated).toLocaleString()}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Card>
    </motion.div>
  );
}
